apiVersion: v1
kind: PersistentVolume
metadata:
  name: DATABASE_PV_PLACEHOLDER
  labels:
    type: local
    app: DB_DISTRO_PLACEHOLDER
    owner-namespace: DATABASE_VOLS_NS_PLACEHOLDER
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: DATABASE_PVC_PLACEHOLDER
  namespace: database-space
  labels:
    app: DB_DISTRO_PLACEHOLDER
    owner-namespace: DATABASE_VOLS_NS_PLACEHOLDER
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
