apiVersion: v1
kind: PersistentVolume
metadata:
  name: decauth-pg-volume
  labels:
    type: local
    app: decauth-pg
    owner-namespace: decauth-volumes
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: decauth-pg-volume-claim
  labels:
    app: decauth-pg
    owner-namespace: decauth-volumes
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
