apiVersion: apps/v1
kind: Deployment
metadata:
  name: DATABASE_DEPLOYMENT_PLACEHOLDER
  namespace: database-space
  labels:
    app: DB_DISTRO_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DB_DISTRO_PLACEHOLDER
  template:
    metadata:
      name: DATABASE_PODS_PLACEHOLDER
      labels:
        app: DB_DISTRO_PLACEHOLDER
    spec:
      containers:
        - name: DB_DISTRO_PLACEHOLDER
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: DATABASE_PVC_PLACEHOLDER
---
apiVersion: v1
kind: Service
metadata:
  name: DATABASE_CLUSTER_PLACEHOLDER
  namespace: database-space
  labels:
    app: DB_DISTRO_PLACEHOLDER
spec:
  type: ClusterIP
  selector:
    app: DB_DISTRO_PLACEHOLDER
  ports:
    - port: 5432
      targetPort: 5432
