name: Docker Build
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      new_tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Build
        run: |
          IMAGE="${{ secrets.docker_username }}/${{ inputs.app_name }}:${{ inputs.new_tag }}"
          docker build -f docker/Dockerfile -t "$IMAGE" .
